name: Build desktop app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    - run: npm install --also=dev

    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: |
        npm run build-mac
        mkdir -p builds/AtticusOS-darwin-universal
        mv path/to/macos/output/AtticusOS.app builds/AtticusOS-darwin-universal/
      env:
        CI: true

    - name: Build for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        npm run build-linux
        mkdir -p builds/AtticusOS-linux-arm64 builds/AtticusOS-linux-x64
        mv path/to/linux-arm64/output/* builds/AtticusOS-linux-arm64/
        mv path/to/linux-x64/output/* builds/AtticusOS-linux-x64/
        zip -r builds/AtticusOS-linux-arm64.zip builds/AtticusOS-linux-arm64
        zip -r builds/AtticusOS-linux-x64.zip builds/AtticusOS-linux-x64

    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: |
        npm run build-windows
        mkdir -p builds/AtticusOS-win32-arm64 builds/AtticusOS-win32-x64
        mv path/to/win32-arm64/output/* builds/AtticusOS-win32-arm64/
        mv path/to/win32-x64/output/* builds/AtticusOS-win32-x64/
        zip -r builds/AtticusOS-win32-arm64.zip builds/AtticusOS-win32-arm64
        zip -r builds/AtticusOS-win32-x64.zip builds/AtticusOS-win32-x64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          builds/AtticusOS-linux-arm64.zip
          builds/AtticusOS-linux-x64.zip
          builds/AtticusOS-win32-arm64.zip
          builds/AtticusOS-win32-x64.zip
          builds/AtticusOS-darwin-universal/AtticusOS.app
        asset_name: |
          AtticusOS-linux-arm64.zip
          AtticusOS-linux-x64.zip
          AtticusOS-win32-arm64.zip
          AtticusOS-win32-x64.zip
          AtticusOS.app
        asset_content_type: application/zip
