name: Build desktop app

on:
  push:
    branches: [ "desktop" ]
  pull_request:
    branches: [ "desktop" ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: desktop  # Ensure the workflow checks out the desktop branch

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    - run: npm install --also=dev

    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: |
        npm run build-mac
      env:
        CI: true

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: desktop  # Ensure the workflow checks out the desktop branch

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          builds/AtticusOS-darwin-universal/AtticusOS.app
        asset_name: |
          AtticusOS.app
        asset_content_type: application/zip
